name: travellory
description: Travel easy, travellory

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: any #0.15.7
  image_picker: ^0.6.1+4
  image_cropper: ^1.2.1
  firebase_auth: 0.15.5+3 #0.15.4 #^0.15.5+2
  cloud_firestore: ^0.13.4+2 #^0.13.4
  firebase_storage: ^3.1.5
  provider: ^4.0.4
  email_validator: ^1.0.4
  flutter_spinkit: ^4.1.2
  firebase_core: 0.4.4+3 #0.4.4 # new
  cloud_functions: 0.4.2+3
  syncfusion_flutter_calendar: ^18.1.42-beta
  font_awesome_flutter: ^8.7.0
  google_maps_flutter: ^0.5.25+3
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  flutter_rounded_date_picker: 1.0.0
  dropdownfield: 1.0.0
  custom_navigation_bar: ^0.2.6
  flushbar: 1.8.0
  logger: ^0.6.0
  path_provider: 1.5.1
  cached_network_image: 2.0.0
  firebase_auth_mocks: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4
  pedantic: ^1.4.0
  build_runner: ^1.2.7


flutter_native_splash:
  image: assets/images/logo/logo_splash.png
  color: "EFE8E8"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/travellory_icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login/
    - assets/images/logo/
    - assets/images/bookings/
    - assets/images/home/trip/
    - assets/images/home/
    - assets/photo_camera.png
    - assets/g_map/
    - assets/g_map/border_points/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FashionFetish
      fonts:
        - asset: assets/fonts/Fashion_Fetish_Regular.ttf
        - asset: assets/fonts/Fashion_Fetish_Italic.ttf
          style: italic
        - asset: assets/fonts/Fashion_Fetish_Bold.ttf
          weight: 600
        - asset: assets/fonts/Fashion_Fetish_Heavy.ttf
          weight: 800
        - asset: assets/fonts/Fashion_Fetish_Light.ttf
          weight: 100
        - asset: assets/fonts/Fashion_Fetish_Light_Italic.ttf
          weight: 100
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
